### PR TITLE
Allow preventing backward navigation on failed validation.

### PR DESCRIPTION
**Pull request by VictorioBerra**
Also:

- extract `stepSelector` and `footerSelector` functionality so it can be called by the user.
- `destroy()`: instead of `empty()` remove the click handlers.

### CODE REVIEW

**Comment by VictorioBerra** [comment]
@oguzhanoya Any chance you can take a quick peek at this?

**Comment by oguzhanoya** [comment]
Thank you for the fix @roilti @VictorioBerra, sorry for the delay.

**Comment by VictorioBerra** [comment]
> Thank you for the fix @roilti @VictorioBerra, sorry for the delay.

    Should I have bumped the version? How do we get this deployed to cdnjs and other places?

**Comment by oguzhanoya** [comment]
> > Thank you for the fix @roilti @VictorioBerra, sorry for the delay.
> 
> ```
> Should I have bumped the version? How do we get this deployed to cdnjs and other places?
> ```

I published a release [(1.0.3)](https://github.com/oguzhanoya/jquery-steps/releases/tag/v1.0.3)

**Pull request merged**
